// Package invoices implements the audit-log helper from ADR-0009 (and
// will host the full invoice flow in phase 6). The audit log ships in
// phase 0 because Austrian §11 UStG compliance benefits from having a
// "show me every invoice for this quarter" export available before
// the first audit request, even when invoices themselves aren't yet
// being generated by the lib.
package invoices

import (
	"time"

	"github.com/bds421/rho-stripe/subject"
)

// Period bounds the [Start, End) window for an audit query.
type Period struct {
	Start time.Time
	End   time.Time
}

// AuditOptions configures the export.
type AuditOptions struct {
	Period Period

	// Format selects the output encoding. Defaults to FormatCSV.
	Format Format
}

// Format is the output encoding for AuditReport.Encode.
type Format string

const (
	FormatCSV  Format = "csv"
	FormatJSON Format = "json"
)

// AuditEntry is one row of the audit report — usually one Stripe
// Invoice, but also includes voided/credit-note rows so the export
// is a complete picture of taxable events in the period.
type AuditEntry struct {
	StripeID         string
	Number           string // Stripe-generated invoice number, or "" for credit notes
	Type             EntryType
	Status           string // "draft" | "open" | "paid" | "void" | "uncollectible"
	CustomerID       string
	CustomerEmail    string
	CustomerVATID    string
	CustomerCountry  string
	Currency         string
	AmountTotal      int64
	AmountTax        int64
	AmountPaid       int64
	Created          time.Time
	Finalized        *time.Time
	Paid             *time.Time
	Voided           *time.Time
	HostedInvoiceURL string
}

// EntryType differentiates invoice rows from credit notes.
type EntryType string

const (
	EntryTypeInvoice    EntryType = "invoice"
	EntryTypeCreditNote EntryType = "credit_note"
)

// AuditReport is the full set of entries for a Period plus the
// totals a tax advisor expects.
type AuditReport struct {
	Period  Period
	Entries []AuditEntry

	// Totals are per-currency: ISO-4217 lowercase code → sum in
	// smallest currency unit. Tax filing aggregates by currency.
	TotalsTotal map[string]int64
	TotalsTax   map[string]int64
	TotalsPaid  map[string]int64
}

// --- Phase 6: invoice creation + send-invoice flow ---

// StripeCustomerID is a typed string for cus_… ids. Alias of
// [subject.StripeCustomerID] — same type as checkout.StripeCustomerID,
// so cross-package handoff needs no conversion.
type StripeCustomerID = subject.StripeCustomerID

// CreateInput is the parameter shape for Operations.CreateDraft. The
// customer must already exist in Stripe (use checkout.CustomerRepo or
// pass the cus_ id directly).
type CreateInput struct {
	Customer  StripeCustomerID
	DueIn     time.Duration // e.g. 30*24*time.Hour for "net 30"
	Memo      string
	LineItems []CreateLineItem
	Metadata  map[string]string

	// NumberOverride lets an app supply its own invoice number for
	// sequential gapless compliance (Austrian §11 UStG). Empty leaves
	// Stripe's auto-numbering active — UNLESS Operations was built
	// with WithNumberRepo, in which case the repo allocates a number
	// from NumberPrefix automatically.
	NumberOverride string

	// NumberPrefix selects the per-prefix sequence the auto-allocator
	// draws from when WithNumberRepo is set and NumberOverride is empty.
	// Typically encodes jurisdiction + year (e.g. "AT-2026-").
	// Ignored when NumberOverride is set or no NumberRepo was wired.
	NumberPrefix string
}

// CreateLineItem is one line on a draft invoice.
type CreateLineItem struct {
	Description string
	Amount      int64  // smallest currency unit
	Currency    string // required
	Quantity    int    // defaults to 1
}

// Invoice is the projection returned by mutating ops + ListOverdue.
type Invoice struct {
	StripeID         string
	Number           string
	Status           string // "draft" | "open" | "paid" | "void" | "uncollectible"
	Customer         StripeCustomerID
	Currency         string
	AmountTotal      int64
	AmountPaid       int64
	DueDate          *time.Time
	HostedInvoiceURL string
	PDFURL           string
}

// CreditNoteInput configures a credit-note (refund / partial refund) issuance.
type CreditNoteInput struct {
	InvoiceID string
	Lines     []CreateLineItem
	Reason    string // 'duplicate' | 'fraudulent' | 'order_change' | 'product_unsatisfactory'
	Refund    bool   // if true, also refunds the payment
}
